package cn.yy.myrent.service.discovery;

public enum HouseReasonCode {
    RECALL_LOCATION_MATCH,
    RECALL_TEXT_MATCH,
    LOCATION_DISTANCE_ADVANTAGE,
    TEXT_RELEVANCE_ADVANTAGE,
    BUDGET_CLOSE_MATCH,
    RENT_MODE_MATCH,
    NEAR_SUBWAY_MATCH,
    PRIVATE_BATHROOM_MATCH,
    HAS_BALCONY_MATCH,
    CIVIL_WATER_ELECTRIC_MATCH,
    SUPPORT_STUDENT_DEPOSIT_FREE_MATCH,
    PRIMARY_PREFERENCE_MATCH,
    SECONDARY_PREFERENCE_MATCH,
    BUDGET_RELAXED_ACCEPTED,
    RELAXED_BUDGET_APPLIED,
    RELAXED_RADIUS_APPLIED,
    FRESH_LISTING
}
