server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rent?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  rabbitmq:
    host: 192.168.100.128
    port: 5672
    username: admin
    password: 123456
    virtual-host: /

  data:
    redis:
      host: 192.168.100.128
      password: 123456
      database: 0

  elasticsearch:
    uris: http://192.168.100.128:9200
    connection-timeout: 5s
    socket-timeout: 30s


knife4j:
  enable: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

canal:
  server:
    host: 127.0.0.1
    port: 11111
    destination: example
    username: canal
    password: Canal@123456
    batchSize: 1000

myrent:
  jwt:
    secret: MyRentJwtSecretChangeMe
    expire-seconds: 86400
