-- 文件名: lock_house.lua
-- KEYS[1] = houseId
-- ARGV[1] = 当前时间戳（可选，用于记录锁定时间）

local key = "house:lock:" .. KEYS[1]

local current = redis.call('GET', key)

-- 如果不存在，说明房源未初始化（可视为可租）
if current == false then
    redis.call('SET', key, '2')

    return 1  -- 成功锁定
end

-- 如果当前是"可租"(1)，则锁定为"已锁定"(2)
if current == '1' then
    redis.call('SET', key, '2')

    return 1  -- 成功锁定
end

-- 否则（已是2），返回失败
return 0---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 黄昊.
--- DateTime: 2026/3/4 13:10
---